retel-io/ari-proxy

- README.md
- drops explicit 'Overview' section
- fixes link to sections containing '&'
> docs: Adjust README toc

- pom.xml
mitigates com.fasterxml.jackson.core:jackson-databind vulnerability
> fix: update jackson-databind dependency to version 2.8.11.1

- debian/ari-proxy.service
- debian/postinst
use paths as specified in https://wiki.debian.org/DebianJavaPackaging
> fix: debian packaging - conform to debian policy

- debian/dirs
- debian/rules
> fix: install systemd template unit file without debhelper

- src/main/java/io/retel/ariproxy/Main.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseKafkaProcessor.java
- src/test/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseKafkaProcessorTest.java
Note: the RestartSource is now being injected in order to control it
during tests.
Co-authored-by: Joeran Vinzens <vinzens@sipgate.de>
> tests: Fix AriCommandsResponseKafkaProcessorTest

- pom.xml
Co-authored-by: Joeran Vinzens <vinzens@sipgate.de>
> fix: Set maven-surefire-plugin version to 3.0.0-M1

- docs/concepts.md
- src/test/java/io/retel/ariproxy/boundary/events/StasisEvents.java
Some inline json has previously been broken (probably during a refactor-rename). This concerned:
- docs example for StasisStart
- mocks for tests
This PR simply "reverted" the affected lines.
> chore: Fix broken stasis event json

- pom.xml
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseKafkaProcessor.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriCommandType.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriMessageType.java
- src/main/java/io/retel/ariproxy/boundary/events/AriEventProcessing.java
- src/main/java/io/retel/ariproxy/health/HealthService.java
We now use jackson over gson anywhere we need a marshaller.
> refactor: Consolidate json marshallers

- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseKafkaProcessor.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseProcessing.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriCommand.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriMessageEnvelope.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriMessageType.java
- src/main/java/io/retel/ariproxy/boundary/events/AriEventProcessing.java
- src/test/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseKafkaProcessorTest.java
- src/test/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseProcessingTest.java
- src/test/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriMessageTypeTest.java
Previously the ari command body as well as the ari message envelope payload (ari response and ari event) have been expected to be or respectively been published as a string with an embedded json object. Treating the entire message as a json object makes the entire marshalling process more convenient.
> feat: treat all nested json objects as such

- pom.xml
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriCommandType.java
> fix: upgrade jackson-databind to v2.9.9

- pom.xml
deals with:
- https://www.cvedetails.com/cve/CVE-2019-12814/
- https://www.cvedetails.com/cve/CVE-2019-14439/
- https://www.cvedetails.com/cve/CVE-2019-14379/
> set jackson-databind version to 2.9.9.1

- pom.xml
due to vulnerabilites in versions < 2.9.10.1
> fix: upgrade jackson-databind to v2.10.2

- src/test/java/io/retel/ariproxy/boundary/callcontext/CallContextProviderTest.java
- src/test/java/io/retel/ariproxy/persistence/PersistentCacheTest.java
this fixes timeout problems during test runs
> test: increase timeout

- CONTRIBUTING.md
- pom.xml
The formatting in this project is not consistent and currently neither a recommendation nor some kind of enforcement of a particular code style exists.
This PR adds [spotless](https://github.com/diffplug/spotless) maven plugin to gradually enforce [Google Java Style](https://google.github.io/styleguide/javaguide.html). Builds will fail, if _changed_ files do not comply with the formatting guidelines. Changed files can be automatically formatted correctly by running ` mvn spotless:apply`.
> Enforce Java Google Style

- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseKafkaProcessor.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseProcessing.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriCommand.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriCommandType.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriResourceRelation.java
- src/test/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseKafkaProcessorTest.java
- src/test/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseProcessingTest.java
- src/test/resources/messages/ari/responses/bridgeCreateResponse.json
- src/test/resources/messages/commands/bridgeCreateCommandWithBody.json
- src/test/resources/messages/responses/bridgeCreateResponseWithBody.json
The feature of including resourceType and Ids in responses introduced in #48 does not work correctly, when resourceIds are only defined in the command's body.
Example:
```
{
"callContext": "CALL_CONTEXT",
"commandId": "COMMAND_ID",
"ariCommand": {
"url": "/bridges",
"body": {
"bridgeId": "BRIDGE_ID",
"name": "BRIDGE_NAME"
},
"method": "POST"
}
}
```
In the current implementation, the newly created bridge `BRIDGE_ID` is not included in the responses `resources`. This is fixed through the PR.
> fix: extract resource from body

- src/main/java/io/retel/ariproxy/boundary/callcontext/CallContextProvider.java
To make logs actionable, it's important to be able to determine for which resource ID the lookup failed.
> feat: log resource id when call context lookup fails

- src/test/resources/messages/commands/channelAnswerCommandWithoutCommandId.json
This test case is confusing: if the command does not need a body, you should not call it with `""` but without any body field.
> fix: remove empty string body from command handling test case

- src/main/resources/application.conf
- src/test/resources/application.conf
Use `ari-proxy` as default value for the `User-Agent` header of the HTTP client (instead of current [default value](https://github.com/akka/akka-http/blob/c0fa9d2/akka-http-core/src/main/resources/reference.conf#L327-L331) `akka-http/${akka.http.version}`).
> feat: use user-agent header 'ari-proxy'

- pom.xml
- src/main/java/io/retel/ariproxy/Main.java
- src/main/java/io/retel/ariproxy/boundary/callcontext/CallContextProvider.java
- src/main/java/io/retel/ariproxy/health/HealthService.java
- src/main/java/io/retel/ariproxy/health/KafkaConnectionCheck.java
- src/main/java/io/retel/ariproxy/health/api/HealthResponse.java
- src/main/java/io/retel/ariproxy/health/api/NewHealthRecipient.java
- src/main/java/io/retel/ariproxy/persistence/PersistentCache.java
- src/test/java/io/retel/ariproxy/health/KafkaConnectionCheckTest.java
This adds an additional HealthProvider to check whether the kafka brokers are reachable and the expected topics are created.
Improves HTTP response body for /health to provide useful error descriptions.
HealthService publishes Message, when he is ready to receive new MonitoringProviders to avoid missing their registration.
Co-authored-by: mia-krause <mia.elisabeth.krause+github@gmail.com>
> feat: introduces connection check for kafka and configured topics

- src/main/resources/application.conf
introduces new default config parameter to ensure correct order of messages even in case of retries
also: set default configs for producer timeouts
- [x ] Signed the [retel.io CLA](https://github.com/retel-io/cla).
- [x ] Made sure there is a corresponding ticket in the project's [issue tracker](https://github.com/retel-io/ari-proxy/issues).
- [x ] Made sure the ticket has been discussed and prioritized by the team.
- [x ] Has appropriate unit tests.
> config: introduce kafka producer config
