- .github/PULL_REQUEST_TEMPLATE.md
> docs: Adjust cla-link name and target in PR template

- service.conf.sample
- src/main/resources/application.conf
- [ X] Signed the [retel.io CLA](https://github.com/retel-io/cla).
- [ X] Made sure there is a corresponding ticket in the project's [issue tracker](https://github.com/retel-io/ari-proxy/issues).
pull request for corresponding issue https://github.com/retel-io/ari-proxy/issues/7
> feature: extract http server port in service.conf

- .gitignore
- Makefile
> fix: Improve/Fix building debian packages 

- README.md
- debian/ari-proxy@.service
- jolokia.properties.sample
> feat: add jolokia agent properties and sample file

- src/main/java/io/retel/ariproxy/Main.java
We exit if the kafka cluster cannot be reached during initialization or if the provided "bootstrap-servers" config value is invalid.
> fix: Exit on KafkaException (during init phase)

- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseKafkaProcessor.java
Co-authored-by: Hekmekk <hekmekk@posteo.de>
> chore: drop println

- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriMessageType.java
> feat: Handle variables of type "ChannelVarset" 

- README.md
- pom.xml
> raise jackson-databind version

- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriCommandType.java
- src/test/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseProcessingTest.java
Co-authored-by: hekmekk <hekmek@posteo.de>
> fix: properly extract resource ID from command /channel/create

- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriMessageType.java
- src/test/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriMessageTypeTest.java
Co-authored-by: Jöran Vinzens <vinzens@sipgate.de>
Co-authored-by: Rea Sand <hekmek@posteo.de>
> feat: support 'BridgeBlindTransfer' ARI events

- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseKafkaProcessor.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriMessageEnvelope.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/CallContextAndCommandRequestContext.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/CommandRequest.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/CommandResponseHandler.java
- src/test/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseKafkaProcessorTest.java
> Add command method and uri in resulting response

- .github/workflows/build.yml
> chore: fetch history for all tags and branches on gh action build

- README.md
Co-authored-by: zwendris <andris.sven@gmail.com>
Co-authored-by: Sven Kube <kube@sipgate.de>
> doc: adds documentstion for Cassandra persistence-store

- service.conf.sample
Co-authored-by: Jöran Vinzens <vinzens@sipgate.de>
> docs: adds cassandra reconnection strategy to sample config

- src/main/java/io/retel/ariproxy/boundary/callcontext/CallContextProvider.java
- src/test/java/io/retel/ariproxy/boundary/callcontext/CallContextProviderTest.java
Co-authored-by: Jöran Vinzens <vinzens@sipgate.de>
> feat: prefer CallContext from ChannelVars in favor of stored CallContext

- src/main/java/io/retel/ariproxy/boundary/callcontext/CallContextProvider.java
> fix: Use key prefix every time keys from the persistent datastore are queried

- debian/control
Co-Authored-by: juliusf <julius.flohr@gmail.com>
> chore: build dependency java17

- docs/metrics.md
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseKafkaProcessor.java
- src/main/java/io/retel/ariproxy/boundary/events/AriEventProcessing.java
- src/main/java/io/retel/ariproxy/boundary/events/WebsocketMessageToProducerRecordTranslator.java
- src/main/java/io/retel/ariproxy/metrics/IncreaseAriEventCounter.java
- src/main/java/io/retel/ariproxy/metrics/MetricsService.java
- src/main/java/io/retel/ariproxy/persistence/CachedKeyValueStore.java
- src/test/java/io/retel/ariproxy/boundary/events/AriEventProcessingTest.java
> rework of metric names, adds meters to count errors

- docs/metrics.md
- src/main/java/io/retel/ariproxy/metrics/Metrics.java
- [x ] Signed the [retel.io CLA](https://github.com/retel-io/cla).
> Add tag for event metric and documentation

- pom.xml
> chore: update log4j2 to 2.17.0

- src/main/java/io/retel/ariproxy/boundary/callcontext/CallContextProvider.java
> feat: add logging for call context generation

- pom.xml
- src/test/java/io/retel/ariproxy/TestUtils.java
- src/test/java/io/retel/ariproxy/boundary/callcontext/CallContextProviderTest.java
- src/test/java/io/retel/ariproxy/boundary/events/AriEventProcessingTest.java
- src/test/java/io/retel/ariproxy/boundary/events/WebsocketMessageToProducerRecordTranslatorITCase.java
> Updating dependencies

- src/main/java/io/retel/ariproxy/boundary/callcontext/CallContextProvider.java
- src/main/java/io/retel/ariproxy/boundary/callcontext/api/RegisterCallContext.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseKafkaProcessor.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseProcessing.java
- src/test/java/io/retel/ariproxy/boundary/callcontext/CallContextProviderTest.java
- src/test/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseProcessingTest.java
> Register call context asynchronously

- src/main/java/io/retel/ariproxy/Main.java
> feat: log service startup and shutdown

- README.md
- src/main/java/io/retel/ariproxy/Main.java
- src/main/java/io/retel/ariproxy/health/AriConnectionCheck.java
- src/main/java/io/retel/ariproxy/health/HealthService.java
- src/main/java/io/retel/ariproxy/health/KafkaConnectionCheck.java
- src/main/java/io/retel/ariproxy/health/api/HealthReport.java
- src/main/resources/application.conf
This checks the services ari-proxy depends on to run
Co-authored-by: Jöran Vinzens <vinzens@sipgate.de>
> feat: introduces /health/backing-services route

- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriCommand.java
- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriCommandType.java
- src/test/java/io/retel/ariproxy/boundary/commandsandresponses/AriCommandResponseKafkaProcessorTest.java
- src/test/resources/messages/commands/channelDeleteWithReasonCommand.json
- src/test/resources/messages/responses/channelDeleteWithReasonResponse.json
- [X ] Signed the [retel.io CLA](https://github.com/retel-io/cla).
- [ X] Made sure there is a corresponding ticket in the project's [issue tracker](https://github.com/retel-io/ari-proxy/issues).
- [ X] Made sure the ticket has been discussed and prioritized by the team.
- [ X] Has appropriate unit tests.
> fix: handle DELETE on a channel with Query Params correctly

- src/main/java/io/retel/ariproxy/boundary/commandsandresponses/auxiliary/AriCommandType.java
- [x ] Signed the [retel.io CLA](https://github.com/retel-io/cla).
- [x ] Made sure the ticket has been discussed and prioritized by the team.
> fix: treat POST to /channels/externalMedia as channel creation
